### ISSUE TITLE
Clarification on Handling Plain Surfaces

### ISSUE THREAD

**Issue by hariharan1412** [ethanweber/nerfbusters#14]
Hello, I really love your application, and I have seen your outputs, and they do a pretty good job. I also understand that you use the Shapenet dataset to train and remove the noise from the point cloud. My project involves a plain surface like a wall, floor, ceiling, etc. Let's say there is a pillory inside the hall. Will the model help me to remove the noise around the pillor or remove the pillor since the pillor is not trained on the shapenet. If I'm right ? Also, what will happen to the wall, ceiling, and floor?

**Comment by ethanweber** [comment]
This should just remove floaters not a full object since it's trained on local shapenet crops and never sees a full object. It'll probably remove textureless regions on walls/planes if they look floater-like. You can also consider trying a method like Bayes' Rays https://bayesrays.github.io/ which models uncertainties directly without a model trained on local crops. Hope this helps to get you started!
