### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by jaidevshriram** [ethanweber/nerfbusters#3]
Hey! Is there an image available to reproduce the environment for this project? I'm having some trouble getting this code working, specifically with functorch (says that `vmap` does not exist) and `tcnn`(`tcnn` not found error -`tinycudann` does exist though).  Still, I think there's a CUDA version issue too w `tinycudann`. I imagine an image would make this a lot easier. 

On a related note, would love to see nerfbusters use the latest release of nerfstudio if possible - as it's quite tough to integrate this into existing pipelines which use the latest release.

**Comment by ethanweber** [comment]
Hey @jaidevshriram, so unfortunately we aren't providing an image for this environment. I'd refer to nerfstudio for getting the environment running (there is some docker support there, though I haven't really tested it), and then you can install this repo with its dependencies. If you wish to use the current version of nerfstudio rather than [our branch](https://github.com/nerfstudio-project/nerfstudio/tree/nerfbusters-changes), you can reference [the PR](https://github.com/nerfstudio-project/nerfstudio/pull/1786) for making code changes. If we make further integrations into the nerfstudio repo, we will update the Nerfbusters documentation. Thanks!
